# JupyterBook settings
# Learn more at https://jupyterbook.org/en/stable/customize/config.html

# Book settings
title: "地震“学”软件"
author: seismo-learn
copyright : "2020–2023"

# Execution settings
execute:
  execute_notebooks: auto
  timeout: 300

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_substitutions:
    # Authors
    田冬冬: "[田冬冬](https://me.seisman.info/)"
    姚家园: "[姚家园](https://github.com/core-man)"
    王亮: "[王亮](https://github.com/wangliang1989)"
    赵志远: "[赵志远](https://github.com/zhaozhiyuan1989)"
    # Platforms
    Linux: "{fab}`linux;fa-brands`"
    macOS: "{fab}`apple;fa-brands`"
    Windows: "{fab}`windows;fa-brands`"
    # Common notes
    install_notes: |
      :::{dropdown} 阅读须知
      1.  我们假定用户已经根据《{doc}`seis101:computer/setup`》中的内容安装了
          C/C++ 和 Fortran 编译器 `gcc`、`g++` 和 `gfortran`
          以及常用命令行工具 `make` 和 `git` 等。
      2.  修改环境变量时，我们假定用户当前使用的 Shell 是 Bash，且 Bash 配置文件
          为 `~/.bashrc`。Z Shell （zsh）用户应修改 `~/.zshrc`。
          不确定自己当前使用的是何种 Shell 的用户，可检查 `echo $SHELL` 命令的输出。
      3.  所有软件的安装方式及安装路径，均遵循
          {doc}`《文件管理实践经验》<seis101:best-practices/file-organization>` 和
          {doc}`《软件安装实践经验》<seis101:best-practices/software-installation>`。
      :::

# HTML-specific settings
html:
  favicon: favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

# Repository settings
repository:
  url: https://github.com/seismo-learn/software
  path_to_book: source
  branch: main

# Advanced sphinx settings
sphinx:
  config:
    intersphinx_mapping:
      seis:
        - https://seismo-learn.org/seismology/
        - null
      seis101:
        - https://seismo-learn.org/seismology101/
        - null
      software:
        - https://seismo-learn.org/software/
        - null
      matplotlib:
        - https://matplotlib.org/stable/
        - null
      numpy:
        - https://numpy.org/doc/stable/
        - null
      obspy:
        - https://docs.obspy.org/
        - null
    copybutton_prompt_text: '>>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}:'
    copybutton_prompt_is_regexp: true
    copybutton_only_copy_prompt_lines: true
    copybutton_remove_prompts: true
